config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/home'
  get 'home/search'
  resources :benefices
  resources :zones
  resources :addresses
  resources :customers do
    collection do
      get 'load'
      post 'import'
      post 'check'
      post 'checkok'
    end
  end
  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"


end

app/views/partials/_header.html.erb
<nav class="navbar navbar-default  navbar-fixed-top">
  <div class="navbar-header">
  <div class="logo_lapiz">

  </div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  
  <div class="navbar-collapse collapse color-menu">
    <ul class="nav navbar-nav nav-personalizado">
    <li>
      <%= link_to "Inicio", root_path, :class => "navbar-link reloadmap" %>  
    </li>
    <li>
     
    </li>


       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Clientes 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li><%= link_to 'Listado Clientes', customers_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Nuevo Cliente", new_customer_path, :class => "dropdown-item" %> </li>
              <li><%= link_to "Importar Clientes", '/customers/load', :class => "dropdown-item" %> </li>
          </ul>
        </li>

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Areas 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
 <li><%= link_to 'Listado Areas', zones_path %></li>
          </ul>
        </li>

    <li>
    
    </li>
    </ul>


        <ul class="nav navbar-nav pull-right">                    

                    <% if user_signed_in? %>
                  <li>
                     <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>        
                  </li>
              <% else %>
                  <li>
                      <%= link_to('Iniciar', new_user_session_path)  %>  
                  </li>
                    <li role="separator" class="divider"></li>
                    <li>
                       <%= link_to('Registrarse', new_user_registration_path)  %>
                  </li>
              <% end %>
      </ul>


            </div>

  </div>
</nav>