config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/home'
  get 'home/search'
  resources :benefices
  resources :zones
  resources :addresses
  resources :customers do
    collection do
      get 'load'
      post 'import'
      post 'check'
      post 'checkok'
    end
  end
  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"


end

app/models/customer.rb
require 'address'
class Customer < ApplicationRecord
	belongs_to :zone,  required: false
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses
									# reject_if: proc {|attributes| attributes['name'].blank?},
									# allow_destroy:true
	def self.import(path, file)
	# 10000,GRAL.RAMIREZ 1968,POSADAS,Misiones,3
		actualizado = 1

		CSV.foreach(path, headers: false) do | row |

			c =  Customer.where(:n_socio => row[0]).first
			if (c)
				c.estado = row[4]				
				actualizado+=1

			else

				c = Customer.new(:n_socio => row[0])
				c.estado = row[4]
				direccion = String(row[1]) + ", " + String(row[2]) + ", " + String(row[3])
				c.addresses.build(:address => direccion)

			end

			c.save
			# puts a.inspect
			
		end

	end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    # @customers = Customer.all
    @customers= Customer.includes(:addresses).all.paginate(page: params[:page], per_page: 10)
    @addres = Address.all

    @map_hash = Gmaps4rails.build_markers(@addres) do |address, marker|
      customer = Customer.select(:nombre, :apellido, :n_socio, :estado).where(:id => address.customer_id).last
      marker.lat address.latitude
      marker.lng address.longitude
      marker.infowindow render_to_string(:partial => "info", :locals =>{:address => address, :customer => customer}) 
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    # @customers= Customer.includes(:addresses).all
      @customers= Customer.includes(:addresses).find(params[:id])
      @addres = Address.where(customer_id: @customers.id).first
      @map_hash = Gmaps4rails.build_markers(@addres) do |address, marker|
      marker.lat address.latitude
      marker.lng address.longitude
      # marker.infowindow [address.address,"</br>", address.latitude,address.latitude].join('-')

      marker.infowindow render_to_string(:partial => "info", :locals =>{:address => @addres, :customer => @customers})
    
    end

  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.addresses.build
  end

  # GET /customers/1/edit
  def edit  
      @customers= Customer.includes(:addresses).find(params[:id])
      @addres = Address.where(customer_id: @customers.id).first
      @map_hash = Gmaps4rails.build_markers(@addres) do |address, marker|
        marker.lat address.latitude
        marker.lng address.longitude
        marker.infowindow [address.address,"</br>", address.latitude,address.latitude].join('-')
    end
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # CHECK /customers/1
  # CHECK /customers/1.json
  def check
    @import = Import.last
    puts @import.state
    render js: @import.state.to_s
  end

  def checkok
    @import = Import.create(state: false)
    puts import.state
  end

  def import
    #Customer.import(params[:file])

    if params[:file].blank?
      flash[:error] = 'Debes seleccionar un archivo valido.'
      redirect_to '/customers/load'
    else
      ext = params[:file]
      ImportWorker.perform_async(ext.path, ext)
      redirect_to root_url, notice: "Los se están importando. Te estaremos avisando cuando estén listos."
    end

  end

  def load
    puts "okokokokokok"
    puts "okokokokokok"
    puts "okokokokokok"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:n_socio, :nombre, :apellido, addresses_attributes: [:id, :address, :latitude, :longitude])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="banner">
<%puts "******editando customer****"%>
<%puts params.inspect%>
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-4 col-xs-12">
      <div class="form-group">
            <%= form.label :n_socio, "Numero de socio:" %>
            <%= form.text_field :n_socio,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-xs-12">
    <div class="form-group">

    <%= form.label :nombre, "Nombre:" %>
            <%= form.text_field :nombre,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
    </div>

  </div>
    <div class="col-md-6 col-xs-12">
    <div class="form-group">
      <%= form.label :apellido, "Apellido:" %>
                <%= form.text_field :apellido,autofocus: true,:required => true, :class=>"form-control input-sm" %>  
          </div>    
    </div>
</div>

<div class="row">
  <div class="col-md-12 col-xs-12">
    <div class="form-group">
          <%= form.fields_for :addresses do |ubicacion|%>
              <%=ubicacion.label :address, "Direccion:"%><br/>
              <%= ubicacion.text_area :address, class: "form-control input-sm" ,rows: 2%>
               <%= ubicacion.hidden_field :latitude%>
                <%= ubicacion.hidden_field :longitude%>
          <%end%>
    </div>
  </div>
</div>

<% if params[:action] == 'edit'%>

      <div class="col-md-12 col-xs-12">
        <!-- <div class="map_mini"> -->
          <div id="map" class="map"></div>
        <!-- </div> -->
      </div>
<%end%>

  <div class="actions">
           <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        <i class="fa fa-floppy-o " aria-hidden="true"></i>
         Guardar
        <% end %>

  </div>
<% end %>

</div>

<script type="text/javascript">
editCustomerMap(<%=raw @map_hash.to_json %>, 2);
</script>

app/views/customers/_info.html.erb
<div class="card">
 

    <h4><i class="fa fa-user-o" aria-hidden="true"></i> <b><%= customer.apellido%>, <%= customer.nombre%></b></h4> 
    <h4>Socio:<b><%= customer.n_socio%></b></h4> 
      <strong>Estado:</strong>
          <% if customer.estado ==1%>
            <i class="fa fa-circle status_1" aria-hidden="true"></i>
          <%end%>
          <% if customer.estado ==2%>
            <i class="fa fa-circle status_2" aria-hidden="true"></i>
          <%end%>
          <% if customer.estado ==3%>
            <i class="fa fa-circle status_3" aria-hidden="true"></i>
          <%end%>
    <p> <i class="fa fa-map-o" aria-hidden="true"></i> <%= address.address%></p> 

</div>

app/views/customers/edit.html.erb
<div class="container">
<div class="banner">
   <h2>Editar Cliente</h2>
</div>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

</div>

app/views/customers/index.html.erb
<div class="container">

<div class="banner">
   <h2>Clientes</h2>
</div>

                                                                                  
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Num. de Socio</th>
        <th>Apellido - Nombre</th>
        <th>Dirección</th>
        <th>Estado</th>
        <th>Acciones</th>
      
      </tr>
    </thead>
    <tbody>
    <%= will_paginate @customers %>  
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.n_socio %></td>
        <td><%= customer.apellido %>, <%= customer.nombre %></td>
        <% customer.addresses.each do |direccion| %>
          <% if (direccion.address)%>
             <td><%= direccion.address %></td>
          <%end%>
        <%end%>
        <td>status</td>
        <td>

            <%= link_to '<i class="fa fa-eye" ></i>'.html_safe, customer_path(customer), class: "btn btn-default btn-view"  %>

            <%= link_to '<i class="fa fa-pencil" ></i>'.html_safe, edit_customer_path(customer), class: "btn btn-default btn-edit"  %>

             <%= link_to '<i class="fa fa-trash-o" ></i>'.html_safe,  customer, method: :delete, data: { confirm: 'Seguro que desea eliminar el cliente?' }, class: "btn btn-default btn-delete"  %>
                
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @customers %> 
  <div class="row">          
 
    <div class="map-system animated fadeOut map-system-down">
        <div id="map" class="map"></div>
    </div> 

  </div>

</div>



<script type="text/javascript">
  createMap(<%=raw @map_hash.to_json %>, 1);
</script>

app/views/customers/load.html.erb
<div class="container">
	<h3>Importar Socios</h3>
		<div class="col-md-6">
			<div class="row">
				<% flash.each do |key, val| %>
					<div class="alert alert-danger alert-dismissable">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>Atenci&oacuten!</strong> <%= val %> 
					</div>
				<% end %>
			</div>
			<div class="jumbotron">
				<%= form_tag import_customers_path, multipart:true do %>
				<%= file_field_tag :file %>
				<%= submit_tag "Importar", class:"btn btn-default" %>
				<% end %>
			</div>
		</div>
</div>

app/views/customers/new.html.erb
<div class="container">
<div class="banner">
   <h2>Nuevo Cliente</h2>
</div>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>


</div>

app/views/customers/show.html.erb
<div class="container">

<div class="banner">
		<!--  <div class="pull-right"> -->
		<!-- accion editar -->
		<%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar'.html_safe, edit_customer_path(@customer),  class: 'btn btn-edit-show'%>  <span>
		<!-- accion volver -->
		<%= link_to '<i class="fa fa-undo" aria-hidden="true"></i> Volver'.html_safe, customers_path,  class: 'btn btn-undo'%>  <span>


		<!-- 	 </div> -->
	</div>

	<div class="banner">

		<div class="row">
			<div class="col-md-6 col-xs-12">
					<div class="form-group">
					<strong>Número de socio:</strong>
					<%= @customer.n_socio %>
				</div>
				<div class="form-group">
					<strong>Socio:</strong>
					<%= @customer.apellido %>, <%= @customer.nombre %>
				</div>
				<div class="form-group">
					<strong>Direccion:</strong>
					<% @customer.addresses.each do |direccion| %>
						<%= direccion.address %>
					<%end%>
				</div>
				<div class="form-group">
					<strong>Estado:</strong>
					<% if @customer.estado ==1%>
						<i class="fa fa-circle status_1" aria-hidden="true"></i>
					<%end%>
					<% if @customer.estado ==2%>
						<i class="fa fa-circle status_2" aria-hidden="true"></i>
					<%end%>
					<% if @customer.estado ==3%>
						<i class="fa fa-circle status_3" aria-hidden="true"></i>
					<%end%>
				</div>
			</div>

			<div class="col-md-6 col-xs-12">
				<div class="map_mini">
					<div id="map" class="map"></div>
				</div>
			</div>

		</div>
	</div>
</div>



<script type="text/javascript">
createMap(<%=raw @map_hash.to_json %>, 2);
</script>